image: Visual Studio 2019
version: 1.0.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '1.0.0.0'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
skip_tags: true
clone_folder: c:\projects\simple-container
platform:
  - Any CPU
configuration:
  - Debug
  - Release
init:
  - git config --global core.autocrlf true
build_script:
  - dotnet build _Src
  - cmd: nuget pack nuget\simple-container.nuspec -OutputDirectory nupkg -Properties Configuration=%CONFIGURATION%;Version=%APPVEYOR_BUILD_VERSION%
test_script:
  - dotnet test _Src --no-restore --no-build
artifacts:
  - path: _Src\Container\bin\$(configuration)\net45
  - path: _Src\Container\bin\$(configuration)\net461
  - path: _Src\Container\bin\$(configuration)\netstandard2.0
  - path: nupkg\*.*
